name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi, thank you for opening up your first issue. Any effort to further the project is greatly appreciated!"
        pr-message: "Hello, thank you for opening up your first pull request. Any effort to further the project is greatly appreciated! Thank you."
